### ISSUE TITLE
Vagrant destroy deletes extra disks, but vagrant up does not recreate

### ISSUE THREAD

**Issue by jameskyle** [att-innovate/occam#22]
Currently if you do a vagrant destroy on one of the ctrl or comps, it deletes the extra disks that were created. However, when you vagrant up that same box. They are not recreated, resulting in failure.

**Comment by pmisiak** [comment]
It this situation you need to run prepare_vagrant.sh script. The script recreates missing disks (only missing, it do not touch existing disks).

**Comment by jameskyle** [comment]
Oh, I migrated that script into a rake task. But the issue was that it wasn't a smooth process. Easy to forget to run the prepare in between.

In my pull request, I've actually put this functionality into vagrant itself. So the disks are created on vagrant up (if they don't exist) and destroyed on vagrant destroy.
