### ISSUE TITLE
Openstack module is tracking fork instead of main.

### ISSUE THREAD

**Issue by jameskyle** [att-innovate/occam#55]
The openstack module being used is Kamil's fork. We should try to get his changes into the main project if they're required for our deployment.

**Comment by kswia** [comment]
@jameskyle: openstack module is no longed under development and contains a bug that had to be fixed for occam. This module should be removed from occam - profiles/roles should use openstack components' modules directly. Until then my forked module should be used.

**Comment by jameskyle** [comment]
coolio.
